name = "TimeRecords"
uuid = "b543fe20-4c68-4b5f-af79-4641a0d39826"
version = "2.1.1"
authors = ["Ruben Gonzalez <ruben.carbonbased@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Dates = "1.10"
FlexUnits = "0.4.4"
RecipesBase = "1.3"
StaticArrays = "1"
Test = "1.10"
julia = "1.10"

[weakdeps]
FlexUnits = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"

[extensions]
FlexUnitsExt = "FlexUnits"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
